version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers: 
      - "syaghoubi00"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    groups:
      # Group GitHub Actions by functionality
      github-actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
      security-actions:
        patterns:
          - "*trivy*"
          - "*anchore*"
          - "*codeql*"
      docker-actions:
        patterns:
          - "docker/*"
          - "*buildx*"
          - "*container*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  # Docker container updates for containers/boxes/fedora
  - package-ecosystem: "docker"
    directory: "/containers/boxes/fedora"
    reviewers: 
      - "syaghoubi00"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    groups:
      containers:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  # Docker container updates for containers/bootc/desktop
  - package-ecosystem: "docker"
    directory: "/containers/bootc/desktop"
    reviewers: 
      - "syaghoubi00"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    groups:
      containers:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5

  # Docker container updates for containers/ansible-dev-tools
  - package-ecosystem: "docker"
    directory: "/containers/ansible-dev-tools"
    reviewers: 
      - "syaghoubi00"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
    groups:
      containers:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
