- name: Prepare Hosts
  become: true
  gather_facts: false
  hosts: all
  tasks:
    - name: Create Ansible Working Directory
      ansible.builtin.file:
        path: "{{ ansible_working_dir }}"
        mode: "0644"
        state: directory
    - name: Create Directory for Storing State
      ansible.builtin.file:
        path: "{{ ansible_state_dir }}"
        mode: "0644"
        state: directory

- name: Update Hosts Packages
  become: true
  hosts: all
  handlers:
    - name: Add Last Update Timestamp
      ansible.builtin.file:
        path: "{{ ansible_state_dir }}/last_update"
        mode: "0644"
        state: touch
  tasks:
    - name: Update All Packages
      when: perform_updates | bool
      block:
        - name: Update APT Systems
          notify: Add Last Update Timestamp
          ansible.builtin.apt:
            package: "*"
            update_cache: true
            autoremove: true
            autoclean: true
            state: latest
          when: ansible_os_family == 'Debian'
        - name: Update DNF Systems
          notify: Add Last Update Timestamp
          ansible.builtin.dnf:
            name: "*"
            state: latest
          when: ansible_os_family == 'RedHat'

- name: Seed lab
  become: true
  hosts: seed
  gather_facts: true
  vars:
    coredns_corefile: ./configs/coredns/Corefile
  roles:
    - coredns

- name: Deploy terraform IaC
  hosts: localhost
  tasks:
    - name: Apply terraform project
      community.general.terraform:
        binary_path: /usr/bin/tofu
        project_path: "./terraform/"
        state: present
