collections:
  - name: syaghoubi00.homelab
    version: ">1.0.0,<2.0.0"
roles:
  - name: coredns
    src: https://github.com/syaghoubi00/ansible-role-coredns
    version: main
  - name: bind
    src: https://github.com/syaghoubi00/ansible-role-bind
    version: main
  - name: docker
    src: https://github.com/syaghoubi00/ansible-role-docker
    version: main
  - name: zfs
    src: https://github.com/syaghoubi00/ansible-role-zfs
    version: main
