collections:
  - name: https://github.com/syaghoubi00/ansible-collection-homelab
    version: main
    type: git
  - name: cloud.terraform
  # # NOTE: 2025-03-29 - Current git repo doesn't have major/minor tags
  # - name: https://github.com/ansible-collections/cloud.terraform
  #   type: git
  #   version: 3.0.0
roles:
  - name: ansible-lockdown.ubuntu24_cis
    src: https://github.com/ansible-lockdown/UBUNTU24-CIS
    version: main
  - name: syaghoubi00-coredns
    src: https://github.com/syaghoubi00/ansible-role-coredns
    version: main
  - name: syaghoubi00-bind
    src: https://github.com/syaghoubi00/ansible-role-bind
    version: main
  - name: syaghoubi00-zfs
    src: https://github.com/syaghoubi00/ansible-role-zfs
    version: main
