collections:
  - name: https://github.com/syaghoubi00/ansible-collection-homelab
    version: main
    type: git
  - name: cloud.terraform
roles:
  - name: syaghoubi00-coredns
    src: https://github.com/syaghoubi00/ansible-role-coredns
    version: main
  - name: syaghoubi00-bind
    src: https://github.com/syaghoubi00/ansible-role-bind
    version: main
  - name: syaghoubi00-zfs
    src: https://github.com/syaghoubi00/ansible-role-zfs
    version: main
