FROM registry.fedoraproject.org/fedora:41

LABEL com.github.containers.toolbox="true"
LABEL org.opencontainers.image.description="Development Toolbox"

# Add dnf conf, since default doesnt install manpages
COPY etc/dnf/dnf.conf /etc/dnf/dnf.conf
RUN dnf install -y \
  ImageMagick-7.1.1.43 \
  ansible-9.13.0 \
  bash-completion-2.16 \
  bat-0.24.0 \
  bind-utils-9.18.33 \
  cargo-1.84.1 \
  cloud-utils-0.33 \
  fd-find-10.1.0 \
  flatpak-spawn-1.0.6 \
  fzf-0.60.0 \
  gcc-14.2.1 \
  git-2.48.1 \
  htop-3.3.0 \
  iperf3-3.17.1 \
  ipmitool-1.8.19 \
  iputils-20240905 \
  jq-1.7.1 \
  libicu-74.2 \
  lm_sensors-3.6.0 \
  man-db-2.12.1 \
  man-pages-6.9.1 \
  ncdu-1.21 \
  neovim-0.10.4 \
  netcat-1.229 \
  opentofu-1.9.0 \
  perl-Image-ExifTool-12.70 \
  pgp-tools-2.10 \
  poetry-1.8.3 \
  python3-neovim-0.5.2 \
  ripgrep-14.1.1 \
  rust-1.84.1 \
  tmux-3.5a \
  tree-2.1.0 \
  unzip-6.0 \
  usbutils-017 \
  xorriso-1.5.6 \
  yq-4.43.1 \
  zoxide-0.9.4 \
  glibc-langpack-en \
  && dnf clean all

# Inatall gh-cli
RUN dnf install -y dnf5-plugins && \
  dnf config-manager addrepo --from-repofile=https://cli.github.com/packages/rpm/gh-cli.repo && \
  dnf install -y gh-2.67.0 --repo gh-cli && \
  dnf clean all

# Install Azure CLI
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
  dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm && \
  dnf install -y azure-cli && dnf clean all

# Install HCP CLI
RUN wget -qO- https://rpm.releases.hashicorp.com/fedora/hashicorp.repo | tee /etc/yum.repos.d/hashicorp.repo && \
  dnf install -y hcp && dnf clean all

# Switched to container
# RUN python3 -m pip --no-cache-dir install molecule molecule-plugins ansible-dev-tools

# Tmp dir for binaries
RUN mkdir /tmp/bin/
# Hugo
RUN hugo_latest_version="$(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name' | cut -c 2-)"; wget -qO /tmp/hugo https://github.com/gohugoio/hugo/releases/latest/download/hugo_extended_${hugo_latest_version}_linux-amd64.tar.gz && \
  tar xzvf /tmp/hugo -C /tmp/bin/ hugo && rm /tmp/hugo
# Docker-compose
RUN wget -qO /tmp/bin/docker-compose https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64

# Kubectl
RUN wget -qO /tmp/bin/kubectl "https://dl.k8s.io/release/$(wget -qO- https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
  cd /tmp/bin/ && \
  echo "$(wget -qO- "https://dl.k8s.io/release/$(wget -qO- https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256") kubectl" | sha256sum --check && \
  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Cleanup tmp
RUN chmod +x /tmp/bin/* && mv /tmp/bin/* /bin && rmdir /tmp/bin/

# Script for running host commands from within the container
COPY host-cmd.sh /usr/bin/host-cmd
# Link podman to host-cmd to pass `podman` commands to host
RUN ln -s /usr/bin/host-cmd /usr/bin/podman

USER toolbox
