## TODO: Setup for services that might have port conflict
- name: Ensure resolved.conf.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: "0755"

- name: Create drop-in to disable systemd-resolve DNSStubListener
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/00-disable-dns-stub-listener.conf
    content: |
      [Resolve]
      DNSStubListener=no
    mode: "0644"

- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted
