- name: Install systemd service
  ansible.builtin.template:
    src: coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    mode: "0644"

## TODO: Make sure there is a port conflict before calling port conflict resolver
- name: Check for any services listening on CoreDNS port
  ansible.builtin.shell: "set -o pipefail; ss -tulnp | grep ':{{ coredns_port }} ' || true"
  register: coredns_port_check
  args:
    executable: /bin/bash
  changed_when: false

- name: Resolve common service conflicts on port 53
  ansible.builtin.include_tasks: resolve-port-conflict.yaml
  # when: # when there is a port conflict - coredns_port_check

- name: Start and enable CoreDNS service
  ansible.builtin.systemd_service:
    name: coredns
    state: started
    enabled: true
    daemon_reload: true
