- name: Remove unofficial Docker packages
  become: true
  ansible.builtin.package:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Add Docker prerequisites
  become: true
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present

- name: Add Docker apt GPG Key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Set architecture variable for repo
  ansible.builtin.set_fact:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' }}"

- name: Add Docker apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker engine
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Set Docker to use local storage driver instead of json
  become: true
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "local"
      }
    mode: "644"

- name: Enable Docker systemd service
  become: true
  ansible.builtin.systemd_service:
    name: docker.service
    state: started
    enabled: true

- name: Enable containerd systemd service
  become: true
  ansible.builtin.systemd_service:
    name: containerd.service
    state: started
    enabled: true
# TODO: Add test to run container to verify function
