name: Create Containerfile Matrix
description: Generates a build matrix using the Containerfiles in the repo

inputs:
  container_dir:
    description: Directory containing Containerfiles
    required: false

outputs:
  matrix:
    description: JSON matrix of containers to build
    value: ${{ steps.build-matrix.outputs.matrix }}

runs:
  using: composite
  steps:
    - name: Build Containerfile Matrix
      id: build-matrix
      shell: bash
      env:
        CONTAINER_DIR: ${{ inputs.container_dir }}
      run: ./.github/actions/create-containerfile-matrix/create-containerfile-matrix.sh
