- name: Local Deployment
  hosts: internal
  become: true
  tasks:
    - name: Add SSH authorized keys to each system
      ansible.posix.authorized_key:
        user: "{{ item.user }}"
        key: "{{ item['keys'] | join('\n') }}"
        # exclusive: true # Delete existing authorized_keys not included in the list
      loop: "{{ ssh_keys }}"
